<?php
mysql_connect("localhost", "root", "");
if(mysql_select_db("nits_recruitment_nf"))
{
	echo "Database nits_recruitment_nf already exists<br/>";
}
else
{
	$q = "CREATE DATABASE nits_recruitment_nf" or die(mysql_error());
	$r = mysql_query($q) or die(mysql_error());
	echo "Database nits_recruitment_nf created successfully<br/>";
}

$q = "CREATE TABLE IF NOT EXISTS user_info (id int(11) NOT NULL auto_increment,
							  reg_id int(11) NOT NULL,
							  email varchar(255) NOT NULL,
							  password varchar(255) NOT NULL,
							  email_verified int(2) NOT NULL,
							  position varchar(50),
							  name_applicant varchar(255),
							  name_father varchar(255),
							  permanent_address text,
							  present_address text,
							  mobile bigint(21),
							  phone_no varchar(15),
							  dob date,
							  dd int(4),
							  mm int(3),
							  yyyy int(4),
							  nationality varchar(50),
							  place_birth varchar(50),
							  caste varchar(11),
							  gender varchar(11),
							  maritial_status varchar(21),
							  PRIMARY KEY (id))";
$r = mysql_query($q) or die(mysql_error());
echo "Table user_info created<br/>"; 	


$q1 = "CREATE TABLE IF NOT EXISTS user_exams(id bigint(21) NOT NULL auto_increment,
													 reg_id int(11) NOT NULL,
													 exam1_name varchar(255),
													 exam1_year int(5),
													 exam1_percentage float(11),
													 exam1_divn varchar(50),
													 exam1_institute varchar(255),
													 exam1_univ varchar(255),
													 exam2_name varchar(255),
													 exam2_year int(5),
													 exam2_percentage float(11),
													 exam2_divn varchar(50),
													 exam2_institute varchar(255),
													 exam2_univ varchar(255),
													 exam3_name varchar(255),
													 exam3_year int(5),
													 exam3_percentage float(11),
													 exam3_divn varchar(50),
													 exam3_institute varchar(255),
													 exam3_univ varchar(255),
													 exam4_name varchar(255),
													 exam4_year int(5),
													 exam4_percentage float(11),
													 exam4_divn varchar(50),
													 exam4_institute varchar(255),
													 exam4_univ varchar(255),
													 exam5_name varchar(255),
													 exam5_year int(5),
													 exam5_percentage float(11),
													 exam5_divn varchar(50),
													 exam5_institute varchar(255),
													 exam5_univ varchar(255),
													 other_edu_details text,
													 PRIMARY KEY (id))";
$r1 = mysql_query($q1) or die(mysql_error());
echo "Table user_exams created<br/>";



$q3 = "CREATE TABLE IF NOT EXISTS user_earlier_posts(id int(11) NOT NULL auto_increment,
													 reg_id int(11) NOT NULL,
													 post1_name varchar(50),
													 post1_from int(5),
													 post1_to int(5),
													 post1_total_year int(3),
													 post1_total_month int(3),
													 post1_institute varchar(255),
													 post1_nature varchar(255),
													 post1_pay varchar(255),
													 post2_name varchar(50),
													 post2_from int(5),
													 post2_to int(5),
													 post2_total_year int(3),
													 post2_total_month int(3),
													 post2_institute varchar(255),
													 post2_nature varchar(255),
													 post2_pay varchar(255),
													 post3_name varchar(50),
													 post3_from int(5),
													 post3_to int(5),
													 post3_total_year int(3),
													 post3_total_month int(3),
													 post3_institute varchar(255),
													 post3_nature varchar(255),
													 post3_pay varchar(255),
													 post4_name varchar(50),
													 post4_from int(5),
													 post4_to int(5),
													 post4_total_year int(3),
													 post4_total_month int(3),
													 post4_institute varchar(255),
													 post4_nature varchar(255),
													 post4_pay varchar(255),
													 post5_name varchar(50),
													 post5_from int(5),
													 post5_to int(5),
													 post5_total_year int(3),
													 post5_total_month int(3),
													 post5_institute varchar(255),
													 post5_nature varchar(255),
													 post5_pay varchar(255),
													 other_posts_details text,
													 PRIMARY KEY(id))";
$r3 = mysql_query($q3) or die(mysql_error());
echo "Tables user_earlier_posts created<br/>";


$q2 = "CREATE TABLE IF NOT EXISTS user_other_details(id int(11) NOT NULL auto_increment,
													 reg_id int(11) NOT NULL,
												     lang_hindi_read int(3),
												     lang_hindi_write int(3),
												     lang_hindi_speak int(3),
													 lang_hindi_exam varchar(255),
												     lang_english_read int(3),
												     lang_english_write int(3),
												     lang_english_speak int(3),
													 lang_english_exam varchar(255),
													 lang_other_1 varchar(255),
													 lang_other_2 varchar(255),
													 lang_other_3 varchar(255),
													 lang_other_exam varchar(255),
													 member_of_prof_body_details text,
													 member_of_ncc_similar_details text,
													 previously_applied_details text,
													 near_relation_1_name varchar(255),
													 near_relation_1_designation varchar(255),
													 near_relation_1_relationship varchar(255),
													 near_relation_2_name varchar(255),
													 near_relation_2_designation varchar(255),
													 near_relation_2_relationship varchar(255),
													 country_1_visited_name varchar(255),
													 country_1_visited_purpose varchar(255),
													 country_1_visited_year int(6),
													 country_2_visited_name varchar(255),
													 country_2_visited_purpose varchar(255),
													 country_2_visited_year int(6),
													 country_3_visited_name varchar(255),
													 country_3_visited_purpose varchar(255),
													 country_3_visited_year int(6),
													 places_resided_1_from varchar(255),
													 places_resided_1_to varchar(255),
													 places_resided_1_address text,
													 places_resided_2_from varchar(255),
													 places_resided_2_to varchar(255),
													 places_resided_2_address text,
													 places_resided_3_from varchar(255),
													 places_resided_3_to varchar(255),
													 places_resided_3_address text,
													 places_resided_4_from varchar(255),
													 places_resided_4_to varchar(255),
													 places_resided_4_address text,
													 additional_remarks text,
													 referee_1_name varchar(255),
													 referee_1_position varchar(255),
													 referee_1_address varchar(255),
													 referee_1_email varchar(255),
													 referee_1_phone varchar(255),
													 certificates text,
													 referee_2_name varchar(255),
													 referee_2_position varchar(255),
													 referee_2_address varchar(255),
													 referee_2_email varchar(255),
													 referee_2_phone varchar(255),
													 dosubmit date,
													 bank_trans_no varchar(50),
													 bank_name_branch text,
													 bank_amount varchar(15),
													 bank_date date,
													 submitted int(2),
													 advertisement_no varchar(20),
													 PRIMARY KEY (id))";
$r2 = mysql_query($q2) or die(mysql_error());
echo "Table user_other_details created<br/>";

?>
